"""Add Relation between the models

Revision ID: 7761d9f16d8b
Revises: bf8e088b780b
Create Date: 2023-12-05 17:26:44.299618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7761d9f16d8b'
down_revision: Union[str, None] = 'bf8e088b780b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'SENT_FOR_APPROVAL', 'APPROVED', name='taskstatus'), nullable=False))
    op.add_column('tasks', sa.Column('assigned_by_id', sa.Integer(), nullable=False))
    op.add_column('tasks', sa.Column('assigned_to_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'tasks', 'users', ['assigned_to_id'], ['id'])
    op.create_foreign_key(None, 'tasks', 'users', ['assigned_by_id'], ['id'])
    op.add_column('users', sa.Column('email', sa.String(length=254), nullable=False))
    op.alter_column('users', 'role',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Enum('admin', 'manager', 'employee', name='role'),
               existing_nullable=False)
    op.drop_index('username', table_name='users')
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index('username', 'users', ['username'], unique=False)
    op.alter_column('users', 'role',
               existing_type=sa.Enum('admin', 'manager', 'employee', name='role'),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('users', 'email')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'assigned_to_id')
    op.drop_column('tasks', 'assigned_by_id')
    op.drop_column('tasks', 'status')
    # ### end Alembic commands ###
