"""Add status and relationships to Task model

Revision ID: 6b01ec7a4b32
Revises: e0f0aea7ab45
Create Date: 2023-12-04 17:34:53.220881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6b01ec7a4b32'
down_revision: Union[str, None] = 'e0f0aea7ab45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# TaskStatus = sa.Enum('PENDING', 'IN_PROGRESS', 'SENT FOR APPROVAL', 'APPROVED')

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    task_status_enum = sa.Enum(TaskStatus, name='task_status_enum')
    task_status_enum.create(op.get_bind(), checkfirst=False)
    op.add_column('tasks', sa.Column('status', task_status_enum, nullable=False, server_default='PENDING'))

    op.add_column('tasks', sa.Column('assigned_by_id', sa.Integer(), sa.ForeignKey('users.id'), nullable=False))
    op.add_column('tasks', sa.Column('assigned_to_id', sa.Integer(), sa.ForeignKey('users.id'), nullable=False))
    op.add_column('users', sa.Column('tasks_assigned_by', sa.Integer(), sa.ForeignKey('tasks.id'), nullable=True))
    op.add_column('users', sa.Column('tasks_assigned_to', sa.Integer(), sa.ForeignKey('tasks.id'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('users', 'tasks_assigned_to')
    op.drop_column('users', 'tasks_assigned_by')
    op.drop_column('tasks', 'assigned_to_id')
    op.drop_column('tasks', 'assigned_by_id')
    op.drop_column('tasks', 'status')
