"""Adding two tables

Revision ID: b8bca04e9e16
Revises: 
Create Date: 2023-11-28 15:56:23.690123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8bca04e9e16'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'users',
    sa.Column('id', sa.Integer, primary_key=True),
    sa.Column('password', sa.String(100), nullable=False),
    sa.Column('username', sa.String(50), nullable=False),
    sa.Column('email', sa.String(254), unique=True, nullable=False),
    sa.Column('role', sa.String(50), nullable=False),
    )
    
    op.create_table(
        'tasks',
    sa.Column('id', sa.Integer, primary_key=True),
    sa.Column('title', sa.String(100), nullable=False),
    sa.Column('description', sa.String(255), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('tasks')
    # ### end Alembic commands ###
